#!/usr/bin/env python3
"""Generates bios_table.zon from DuckStation's BIOS table (src/core/bios.cpp, 0BSD).

    python3 ps1-core/src/resources/gen_bios_table.py duckstation_ref/src/core/bios.cpp <commit> \
        > ps1-core/src/resources/bios_table.zon

Only the PS1 images are kept. DuckStation's PS2 rows hash a whole 4 MB image,
and this core takes 512 KB, so they could never match. A data row this script
cannot parse is an error, so an upstream change of layout cannot drop rows
silently.
"""

import re
import sys

ROW = re.compile(
    r'^\s*\{\s*"(?P<description>[^"]+)"\s*,\s*"(?P<version>[^"]+)"\s*,\s*(?:nullptr|"[^"]*")\s*,\s*'
    r'ConsoleRegion::(?P<region>\w+)\s*,\s*(?:true|false)\s*,\s*ImageInfo::FastBootPatch::\w+\s*,\s*\d+\s*,\s*'
    r'MakeHashFromString\("(?P<md5>[0-9a-f]{32})"\)\s*\},\s*$'
)

REGIONS = {"NTSC_J": "japan", "NTSC_U": "america", "PAL": "europe"}


def models(description):
    """"SCPH-1001, 5003, DTL-H1201, H3001 (v2.2 ...)" -> SCPH-1001, SCPH-5003,
    DTL-H1201, DTL-H3001: a name with no prefix inherits the one before it."""
    names = description.split(" (", 1)[0].split(", ")
    out = []
    prefix = None
    for name in names:
        if "-" in name:
            prefix = name[: name.index("-") + 1]
            out.append(name)
        elif prefix is None:
            sys.exit(f"model {name!r} has no prefix to inherit in {description!r}")
        else:
            out.append(prefix + name)
    return out


def main():
    if len(sys.argv) != 3:
        sys.exit("usage: gen_bios_table.py <bios.cpp> <duckstation commit>")
    path, commit = sys.argv[1], sys.argv[2]

    rows = []
    for line in open(path, encoding="utf-8"):
        if 'MakeHashFromString("' not in line:
            continue
        m = ROW.match(line)
        if m is None:
            sys.exit(f"unparsed BIOS row: {line.strip()}")
        if m["description"].startswith("PS2"):
            continue
        if m["region"] not in REGIONS:
            sys.exit(f"PS1 row with region {m['region']}: {m['description']}")
        rows.append(m)

    print(f"// Generated by gen_bios_table.py from DuckStation {commit}")
    print("// src/core/bios.cpp (0BSD). Do not edit. Read through bios.zig.")
    print(".{")
    for m in rows:
        names = ", ".join(f'"{n}"' for n in models(m["description"]))
        print(
            f'    .{{ .md5 = "{m["md5"]}", .description = "{m["description"]}", '
            f'.version = "{m["version"]}", .region = .{REGIONS[m["region"]]}, '
            f".models = .{{ {names} }} }},"
        )
    print("}")


if __name__ == "__main__":
    main()
